name: CI - Run Tests & Publish Allure

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}-

      - name: Run tests (headless)
        env:
          HEADLESS: "true"
          CHROME_BIN: /usr/bin/google-chrome
        run: |
          mvn -B -Pci test -Dheadless=true -Dallure.results.directory=target/allure-results

      - name: Upload allure-results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

  publish-report:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v4

      - name: Download allure-results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: ./allure-results

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: ./allure-results
          allure_report: ./allure-report
          keep_reports: 10

      - name: List report files
        run: ls -la ./allure-report | sed -n '1,80p'

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-report
          force_orphan: true
          enable_jekyll: false